name: Angular CI/CD to IIS
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      BUILD_OUTPUT: www
      IIS_PATH: C:\TestCICD-manish
      BACKUP_ROOT: C:\TestCICD-manishBackup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
        
      - name: Install dependencies
        run: npm ci

      - name: Build Ionic app
        run: ionic build --prod

      - name: Deploy to IIS folder
        shell: powershell
        run: |
          $source = Join-Path $env:GITHUB_WORKSPACE "$env:BUILD_OUTPUT\*"
          $destination = $env:IIS_PATH
          $backupRoot = $env:BACKUP_ROOT
          $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
          $backupPath = Join-Path $backupRoot $timestamp
                if (Test-Path $destination) {
            New-Item -ItemType Directory -Path $backupPath -Force | Out-Null
            Copy-Item -Path "$destination\*" -Destination $backupPath -Recurse -Force -ErrorAction SilentlyContinue
            Write-Host "Backup created at $backupPath"
          }
          if (-not (Test-Path $destination)) {
            New-Item -ItemType Directory -Path $destination -Force | Out-Null
          }

          Remove-Item -Path "$destination\*" -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item -Path $source -Destination $destination -Recurse -Force
          Write-Host "Deployed to $destination"

          $allBackups = Get-ChildItem -Path $backupRoot -Directory -ErrorAction SilentlyContinue | Sort-Object CreationTime -Descending
           if ($allBackups.Count -gt 5) {
           $allBackups | Select-Object -Skip 5 | Remove-Item -Recurse -Force}
